#!/bin/bash -   
#title          :iqtree.sh
#description    :For phylogenomic tree https://merenlab.org/2017/06/07/phylogenomics/
#author         :Julius Nweze
#date           :20230809
#version        :v1
#usage          :Go to the Analysis folder and run./iqtree.sh
#==============================================================================================

# 
# Activate anvio environment
#    conda activate anvio-dev

# Get file list and rename them

# ls original_fasta/*.fna > Rename_files.txt


#Produce external-genomes.txt file from Database folder in TAB characters
# Database
#  ls *.db > external-genomes.txt

# Only include .db in column two

# Eg. 
#    name	contigs_db_path
#    MAG1	Database/MAG1.db
#    MAG2	Database/MAG2.db


wkdir="~/proj/Peat_soil/Methylobacter_hq_nr/Data"

# Change the working directory to the specified directory
cd "$wkdir"


# We will use the program anvi-get-sequences-for-hmm-hits to get sequences out of this collection of contigs databases.
# We will concatenate genes, but which genes are we going to concatenate?


    anvi-get-sequences-for-hmm-hits --external-genomes external_genomes.txt --hmm-source Bacteria_71 --list-available-gene-names &&

# GENES IN HMM SOURCES COMMON TO ALL GENOMES

* Bacteria_71 [type: singlecopy]: ADK, AICARFT_IMPCHas, ATP-synt, ATP-synt_A,                                                                                                                                                                 
  Adenylsucc_synt, Chorismate_synt, EF_TS, Exonuc_VII_L, GrpE, Ham1p_like, IPPT,                                                                                                                                                              
  OSCP, PGK, Pept_tRNA_hydro, RBFA, RNA_pol_L, RNA_pol_Rpb6, RRF, RecO_C,                                                                                                                                                                     
  Ribonuclease_P, Ribosom_S12_S23, Ribosomal_L1, Ribosomal_L13, Ribosomal_L14,                                                                                                                                                                
  Ribosomal_L16, Ribosomal_L17, Ribosomal_L18p, Ribosomal_L19, Ribosomal_L2,                                                                                                                                                                  
  Ribosomal_L20, Ribosomal_L21p, Ribosomal_L22, Ribosomal_L23, Ribosomal_L27,                                                                                                                                                                 
  Ribosomal_L27A, Ribosomal_L28, Ribosomal_L29, Ribosomal_L3, Ribosomal_L32p,                                                                                                                                                                 
  Ribosomal_L35p, Ribosomal_L4, Ribosomal_L5, Ribosomal_L6, Ribosomal_L9_C,                                                                                                                                                                   
  Ribosomal_S10, Ribosomal_S11, Ribosomal_S13, Ribosomal_S15, Ribosomal_S16,                                                                                                                                                                  
  Ribosomal_S17, Ribosomal_S19, Ribosomal_S2, Ribosomal_S20p, Ribosomal_S3_C,
  Ribosomal_S6, Ribosomal_S7, Ribosomal_S8, Ribosomal_S9, RsfS, RuvX, SecE,
  SecG, SecY, SmpB, TsaE, UPF0054, YajC, eIF-1a, ribosomal_L24, tRNA-synt_1d,
  tRNA_m1G_MT




# You can select any combination of these genes to use for your phylogenomic analysis, including all of them –if you do not declare a --gene-names parameter, the program would use all. But considering the fact that ribosomal proteins are often used for phylogenomic analyses, let’s say we decided to use 39 ribosomal proteins. It will generate a concatenated gene alignments. Aligner is MUSCLE 

mkdir iqtree_file

# Use all
anvi-get-sequences-for-hmm-hits --external-genomes external_genomes.txt -o concatenated-proteins.fa --hmm-source Bacteria_71 --return-best-hit --get-aa-sequences --concatenate

# extract all the gene hits to know which one is available
anvi-script-gen-hmm-hits-matrix-across-genomes --external-genomes external_genomes.txt --hmm-source Bacteria_71 -o Bacteria_71_hmm_hits.txt

# Know which genome has 16S

anvi-script-gen-hmm-hits-matrix-across-genomes --external-genomes external_genomes.txt --hmm-source Ribosomal_RNA_16S -o 16S_hmm_hits.txt
#====================================================================================================================
#    anvi-get-sequences-for-hmm-hits --external-genomes external_genomes.txt -o concatenated-proteins.fa --hmm-source Bacteria_71 --gene-names Ribonuclease_P,Ribosom_S12_S23,Ribosomal_L1,Ribosomal_L13,Ribosomal_L14,Ribosomal_L16,Ribosomal_L17,Ribosomal_L18p,Ribosomal_L19,Ribosomal_L2,Ribosomal_L20,Ribosomal_L21p,Ribosomal_L22,Ribosomal_L23,Ribosomal_L27,Ribosomal_L27A,Ribosomal_L28,Ribosomal_L29,Ribosomal_L3,Ribosomal_L32p,Ribosomal_L35p,Ribosomal_L4,Ribosomal_L5,Ribosomal_L6,Ribosomal_L9_C,Ribosomal_S10,Ribosomal_S11,Ribosomal_S13,Ribosomal_S15,Ribosomal_S16,Ribosomal_S17,Ribosomal_S19,Ribosomal_S2,Ribosomal_S20p,Ribosomal_S3_C,Ribosomal_S6,Ribosomal_S7,Ribosomal_S8,Ribosomal_S9 --return-best-hit --get-aa-sequences --concatenate &&



# Using only 31 USCGs

#    anvi-get-sequences-for-hmm-hits --external-genomes external_genomes.txt -o concatenated-proteins.fa --hmm-source Bacteria_71 --gene-names Ribosom_S12_S23,Ribosomal_L1,Ribosomal_L13,Ribosomal_L14,Ribosomal_L16,Ribosomal_L17,Ribosomal_L19,Ribosomal_L2,Ribosomal_L20,Ribosomal_L22,Ribosomal_L23,Ribosomal_L27,Ribosomal_L28,Ribosomal_L29,Ribosomal_L3,Ribosomal_L4,Ribosomal_L5,Ribosomal_L6,Ribosomal_S10,Ribosomal_S11,Ribosomal_S13,Ribosomal_S15,Ribosomal_S16,Ribosomal_S17,Ribosomal_S19,Ribosomal_S2,Ribosomal_S6,Ribosomal_S7,Ribosomal_S8,Ribosomal_S9,ribosomal_L24 --return-best-hit --get-aa-sequences --concatenate

#====================================================================================================================
 # mkdir 16S
# Get full length 16S RNA from genomes
#    for i in Database/*.db; do anvi-get-sequences-for-hmm-hits -c $i --hmm-source Ribosomal_RNA_16S -o 16S/$(basename $i .db).fa --return-best-hit; done

#    anvi-get-sequences-for-hmm-hits --external-genomes external_genomes.txt -o 16S_concatenated-sequences.fa --hmm-source Ribosomal_RNA_16S --return-best-hit --concatenate

#====================================================================================================================
# Activate the maft environment
conda activate mafft_env

mkdir iqtree_file
# align the sequences
mafft --auto concatenated-proteins.fa > 16S_concatenated-sequences.fa

# Strategy: FFT-NS-2 (Fast but rough)

#==============================================================================================
# MAG0 is the name of the outgroup   
# Ultrafast bootstrap with -bb 1000 replicates
# Use iqtree to construct the tree
# example.phy.iqtree: the main report file that is self-readable. You should look at this file to see the computational results. It also contains a textual representation of the final tree (see below).
# example.phy.treefile: the ML tree in NEWICK format, which can be visualized by any supported tree viewer programs like FigTree or iTOL.

cd ~/proj/Peat_soil/Methylobacter_hq_nr/Data/iqtree_file

 iqtree -s concatenated-proteins_aln.fa -o MAG45 -nt 10 -m MFP -bb 1000

# Visualise the tree ****.treefile in

# Upload tree into Itol








